### ISSUE TITLE
Could you please add some missing KMP targets and publish a new version?

### ISSUE THREAD

**Issue by deusaquilus** [sschr15/jetbrains-annotations-kmp#1]
Hi, I see some targets in your list (e.g. tvos_arm64) that are not in the tooling metadata file:
https://repo1.maven.org/maven2/com/sschr15/annotations/jb-annotations-kmp/24.1.0/jb-annotations-kmp-24.1.0-kotlin-tooling-metadata.json

That means when I try to build with these targets it breaks:
```
      - Other compatible attribute:
          - Doesn't say anything about its target Java environment (preferred optimized for non-jvm)
  - Variant 'androidNativeArm64ApiElements-published' capability com.sschr15.annotations:jb-annotations-kmp:24.1.0 declares a library for use during 'kotlin-api', as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'native':
      - Incompatible because this component declares a component, as well as attribute 'org.jetbrains.kotlin.native.target' with value 'android_arm64' and the consumer needed a component, as well as attribute 'org.jetbrains.kotlin.native.target' with value 'tvos_arm64'
      - Other compatible attribute:
```

Any chance you can add these targets to your build.gradle.kts and publish a new version?
```
tvosX64()
tvosArm64()
watchosX64()
watchosArm32()
watchosArm64()
watchosX64()
```

**Comment by sschr15** [comment]
If all goes well, this should be present in `24.1.0+apple` soon (after the [run](https://github.com/sschr15/jetbrains-annotations-kmp/actions/runs/10950852467/job/30406866748) finishes)

**Comment by deusaquilus** [comment]
Thanks!

**Comment by sschr15** [comment]
Despite the build failing, the artifacts [should now be published](https://repo1.maven.org/maven2/com/sschr15/annotations/jb-annotations-kmp/24.1.0+apple/).

**Comment by deusaquilus** [comment]
Doesn't it need to have a 24.1.0+apple version here?
https://repo1.maven.org/maven2/com/sschr15/annotations/jb-annotations-kmp/

**Comment by deusaquilus** [comment]
Ah, I see it on s01. Maybe it just hasn't made its way over to repo1.
![image](https://github.com/user-attachments/assets/c793d8a8-42c7-4987-b736-7353baebf010)

**Comment by sschr15** [comment]
It made its way there, but the graphical view is slow to update apparently
